### ISSUE TITLE
train-en2any-ST script

### ISSUE THREAD

**Issue by jamfly** [Glaciohound/Chimera-ST#1]
Hi,

Thank for this amazing work, however, the `train-en2any-ST` script, which described in README section seems missing.

**Comment by Glaciohound** [comment]
Hi I apologize for having left this project for a while, and did not notice your issue.

I forgot to post the scripts you mentioned and now you should be able to see them. Hope this should be helpful to you!

(If you think this issue has been solved, you could close it. ^_^)
