### ISSUE TITLE
some question on your shared image

### ISSUE THREAD

**Issue by renrenzsbbb** [Glaciohound/Chimera-ST#2]
Thanks for your great work. I watch your report in techbeat. I has a question that in the below image, you say dirrerent color represent different semantic. However, in your grapg, one color may has two clusters like green and blue. It means that it contain different semantic infromation? Thanks
![image](https://user-images.githubusercontent.com/30514838/129432218-b67b8970-d02f-4653-b768-8254afc2ff2e.png)

**Comment by Glaciohound** [comment]
Hi, thank you for your question. Actually they should be similar but distinct colors. The root causes include:
1. Due a large number of colors (16) I need to choose, it is a bit hard now difficult to make them all very different from each other in the color space.
2. I added fading effects when making the video, so a near but dark color and a far but bright color might seem similar.

A list of colors I used:
```
colors = ['r', 'g', 'b', 'c',
          'm', 'y', 'w', 'dimgray',
          'tan', 'salmon', 'navy', 'violet',
          'pink', 'limegreen', 'aqua', 'darkorange']
```

Hope this information helps. Let me know if you have other questions about this!
