### ISSUE TITLE
some version problem

### ISSUE THREAD

**Issue by tjshu** [Glaciohound/Chimera-ST#4]
Chimera-ST/chimera/prepare_data/prep_mustc_data.py
88  change to sample_rate = torchaudio.info(wav_path).sample_rate
114  change to waveform, _ = torchaudio.load( wav_path, frame_offset=offset, num_frames=n_frames)

**Comment by Glaciohound** [comment]
Can you (or any other people facing similar problems) note down what versions you are using? This information might be helpful all users to source the bugs according to their system configurations.

**Comment by tjshu** [comment]
sorry,I did not save version information
